### ISSUE TITLE
Parser contains limited information, it doesn't show error lines

### ISSUE THREAD

**Issue by tailtq** [imrim12/formkl#25]
# Expected Behavior

The parser doesn't work as expected, it should display the lines where the error lies on. Instead, it only shows `Unexpected token ...` and the traceback in the library.

## Failure Information (for bugs)

```
/Users/username/test/test.js:25
  throw err;
  ^

SyntaxError: Unexpected token: "h"
    at d.getNextToken (/Users/username/test/node_modules/formkl/dist/index.cjs:1:1968)
    at d.getNextToken (/Users/username/test/node_modules/formkl/dist/index.cjs:1:1930)
    at L._eat (/Users/username/test/node_modules/formkl/dist/index.cjs:2:8437)
    at L.StringLiteral (/Users/username/test/node_modules/formkl/dist/index.cjs:2:8008)
    at L.SectionBlock (/Users/username/test/node_modules/formkl/dist/index.cjs:2:1886)
    at L.SectionBlockList (/Users/username/test/node_modules/formkl/dist/index.cjs:2:1540)
    at L.FormBlock (/Users/username/test/node_modules/formkl/dist/index.cjs:2:1070)
    at L.parse (/Users/username/test/node_modules/formkl/dist/index.cjs:2:398)
    at Object.<anonymous> (/Users/username/test/test.js:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
```

## Steps to Reproduce

Below is my code which I intentionally remove the character `s` in the "Personal Information" line:
```
const { Parser: FormklParser } = require('formkl');

try {
  const text = `
    formkl "Your Formkl example" "This form is generated by the formkl adapter" {
      multiple "Work Experience" has {
        require text;
      }
      "Personal Information" ha{
        text;
        multiple paragraph;
        multiple text as "something";
      }
    }
  `;
  new FormklParser().parse(text);
} catch (err) {
  throw err;
}
````

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS Monetery 12.6.2
* Library version: Both 1.0.0-rc.4 and 1.0.0-rc.5

**Comment by imrim12** [comment]
Resolved in this commit [c0976d5](https://github.com/imrim12/formkl/commit/c0976d512e5a3637fd904f949672b08008abd753), thank for the catch!
